import re

translations_file = r"d:\SIH2026\Smriti\apps\patient\lib\l10n\app_translations.dart"

with open(translations_file, 'r', encoding='utf-8') as f:
    code = f.read()

# 1. Clean languages map at top
clean_languages_block = """  static const Map<String, Map<String, String>> languages = {
    'en': {
      'name': 'English',
      'nativeName': 'English',
    },
    'hi': {
      'name': 'Hindi',
      'nativeName': 'हिंदी',
    },
    'as': {
      'name': 'Assamese',
      'nativeName': 'অসমীয়া',
    },
    'bn': {
      'name': 'Bengali',
      'nativeName': 'বাংলা',
    },
    'lus': {
      'name': 'Mizo',
      'nativeName': 'Mizo',
    },
    'mni': {
      'name': 'Manipuri',
      'nativeName': 'মৈতৈলোন্',
    },
  };"""

# Replace languages block
pattern_lang = r"  static const Map<String, Map<String, String>> languages = \{.*?\n  \};"
code = re.sub(pattern_lang, clean_languages_block, code, flags=re.DOTALL)

# 2. Define gameplay keys dictionary
new_keys = {
    'en': {
        'header.todayReminders': "Today's Reminders",
        'games.letPlay': "Let's Play",
        'gameplay.finalScore': 'FINAL SCORE',
        'gameplay.bestScore': 'BEST SCORE',
        'gameplay.home': 'Home',
        'gameplay.playAgain': 'Play Again',
        'gameplay.greatJob': 'Great Job!',
        'gameplay.activityCompleted': 'Activity Completed',
        'gameplay.gamePaused': 'Game Paused',
        'gameplay.resumeSession': 'Resume Session',
        'gameplay.endSession': 'End Game Session',
        'gameplay.sayVoice': 'Say ',
        'gameplay.pauseVoiceHint': 'Say "Resume" or "Home"',
        'gameplay.accuracy': 'Accuracy',
        'gameplay.avgSpeed': 'Avg Speed',
        'gameplay.bestStreak': 'Best Streak',
        'gameplay.level': 'Level {level}',
        'gameplay.round': 'Round {round} / {total}',
        'gameplay.trial': 'Trial {trial} / {total}',
        'gameplay.stage': 'Stage {stage}',
        'gameplay.step': 'Step {step} / {total}',
        'gameplay.getReady': 'Get Ready',
        'gameplay.memorizeTiles': 'Memorize the {count} tiles',
        'gameplay.rememberAndRecognize': 'Remember and recognize in the next screen',
        'gameplay.selectDifficulty': 'Select Difficulty Level',
        'gameplay.difficultySettings': 'Difficulty Settings',
        'gameplay.chooseStartingChallenge': 'Choose starting challenge (1 to 12)',
        'gameplay.difficultyPreset': 'Difficulty Preset (1–10)',
        'gameplay.traditionalKang': 'Traditional Manipuri Kangshang',
        'gameplay.aimAndStrikeVoice': 'Pull back to aim & strike • Voice: ',
        'gameplay.aimAndStrike': 'Round {round} of {total} • Aim & Strike',
        'gameplay.tapOnTarget': 'Tap on the target! 🎯',
        'gameplay.tapTargetHint': 'Hint: Tap on the target circle',
        'gameplay.danceStages': 'Dance Stages (1–6)',
        'gameplay.doneCount': 'Done: {count}',
        'gameplay.findItem': 'Find this Item',
        'gameplay.findItems': 'Find all {count} items',
        'gameplay.memorizeItem': 'Memorize item',
        'gameplay.imReady': "I'm Ready!",
        'gameplay.toggleSound': 'Toggle Sound',
        'gameplay.pauseResumeGame': 'Pause or Resume Game',
        'gameplay.exitToHome': 'Exit to Home',
        'gameplay.closeCall': 'Close call! Keep your focus',
        'gameplay.gentlePush': 'A gentle push! Slide a little further',
        'gameplay.goodForce': 'Good force! Try a softer touch',
    },
    'hi': {
        'header.todayReminders': 'आज के रिमाइंडर',
        'games.letPlay': 'आइए खेलें',
        'gameplay.finalScore': 'अंतिम स्कोर',
        'gameplay.bestScore': 'सर्वश्रेष्ठ स्कोर',
        'gameplay.home': 'होम',
        'gameplay.playAgain': 'फिर खेलें',
        'gameplay.greatJob': 'बहुत बढ़िया!',
        'gameplay.activityCompleted': 'गतिविधि पूरी हुई',
        'gameplay.gamePaused': 'खेल रुका हुआ है',
        'gameplay.resumeSession': 'खेल जारी रखें',
        'gameplay.endSession': 'खेल समाप्त करें',
        'gameplay.sayVoice': 'बोलें ',
        'gameplay.pauseVoiceHint': '"जारी रखें" या "होम" बोलें',
        'gameplay.accuracy': 'सटीकता',
        'gameplay.avgSpeed': 'औसत गति',
        'gameplay.bestStreak': 'सर्वश्रेष्ठ लय',
        'gameplay.level': 'स्तर {level}',
        'gameplay.round': 'दौर {round} / {total}',
        'gameplay.trial': 'प्रयास {trial} / {total}',
        'gameplay.stage': 'चरण {stage}',
        'gameplay.step': 'कदम {step} / {total}',
        'gameplay.getReady': 'तैयार हो जाएं',
        'gameplay.memorizeTiles': '{count} टाइलों को याद रखें',
        'gameplay.rememberAndRecognize': 'याद रखें और अगली स्क्रीन पर पहचानें',
        'gameplay.selectDifficulty': 'कठिनाई स्तर चुनें',
        'gameplay.difficultySettings': 'कठिनाई सेटिंग्स',
        'gameplay.chooseStartingChallenge': 'शुरुआती चुनौती चुनें (1 से 12)',
        'gameplay.difficultyPreset': 'कठिनाई प्रीसेट (1–10)',
        'gameplay.traditionalKang': 'पारंपरिक मणिपुरी कांगशांग',
        'gameplay.aimAndStrikeVoice': 'निशाना लगाने के लिए खींचें और मारें • आवाज: ',
        'gameplay.aimAndStrike': 'दौर {round} / {total} • निशाना लगाएं और मारें',
        'gameplay.tapOnTarget': 'लक्ष्य पर टैप करें! 🎯',
        'gameplay.tapTargetHint': 'संकेत: लक्ष्य वृत्त पर टैप करें',
        'gameplay.danceStages': 'नृत्य चरण (1–6)',
        'gameplay.doneCount': 'पूर्ण: {count}',
        'gameplay.findItem': 'यह वस्तु खोजें',
        'gameplay.findItems': 'सभी {count} वस्तुएं खोजें',
        'gameplay.memorizeItem': 'वस्तु याद रखें',
        'gameplay.imReady': 'मैं तैयार हूँ!',
        'gameplay.toggleSound': 'आवाज़ चालू/बंद करें',
        'gameplay.pauseResumeGame': 'खेल रोकें या जारी रखें',
        'gameplay.exitToHome': 'होम पर वापस जाएं',
        'gameplay.closeCall': 'बहुत करीब! ध्यान बनाए रखें',
        'gameplay.gentlePush': 'हल्का धक्का! थोड़ा और आगे खिसकाएं',
        'gameplay.goodForce': 'अच्छा बल! थोड़ा हल्का स्पर्श आज़माएं',
    },
    'as': {
        'header.todayReminders': 'আজিৰ ৰিমাইণ্ডাৰসমূহ',
        'games.letPlay': 'আহক খেলোঁ',
        'gameplay.finalScore': 'চূড়ান্ত নম্বৰ',
        'gameplay.bestScore': 'শ্ৰেষ্ঠ নম্বৰ',
        'gameplay.home': 'ঘৰ',
        'gameplay.playAgain': 'পুনৰ খেলক',
        'gameplay.greatJob': 'বৰ ধুনীয়া!',
        'gameplay.activityCompleted': 'কাৰ্যসূচী সমাপ্ত হ’ল',
        'gameplay.gamePaused': 'খেল স্থগিত কৰা হৈছে',
        'gameplay.resumeSession': 'খেল আকৌ আৰম্ভ কৰক',
        'gameplay.endSession': 'খেল সমাপ্ত কৰক',
        'gameplay.sayVoice': 'কওক ',
        'gameplay.pauseVoiceHint': '"আৰম্ভ কৰক" বা "ঘৰ" কওক',
        'gameplay.accuracy': 'সঠিকতা',
        'gameplay.avgSpeed': 'গড় গতি',
        'gameplay.bestStreak': 'শ্ৰেষ্ঠ ধাৰাবাহিকতা',
        'gameplay.level': 'স্তৰ {level}',
        'gameplay.round': 'ৰাউণ্ড {round} / {total}',
        'gameplay.trial': 'চেষ্টা {trial} / {total}',
        'gameplay.stage': 'স্তৰ {stage}',
        'gameplay.step': 'পদক্ষেপ {step} / {total}',
        'gameplay.getReady': 'প্ৰস্তুত হওক',
        'gameplay.memorizeTiles': '{count} টা টাইল মনত ৰাখক',
        'gameplay.rememberAndRecognize': 'মনত ৰাখক আৰু পিছৰ পৰ্দাত চিনাক্ত কৰক',
        'gameplay.selectDifficulty': 'কঠিনতাৰ স্তৰ বাছনি কৰক',
        'gameplay.difficultySettings': 'কঠিনতাৰ ছেটিংছ',
        'gameplay.chooseStartingChallenge': 'প্ৰাৰম্ভিক প্ৰত্যাহ্বান বাছক (১ ৰ পৰা ১২)',
        'gameplay.difficultyPreset': 'কঠিনতাৰ প্ৰিসেট (১–১০)',
        'gameplay.traditionalKang': 'পৰম্পৰাগত মণিপুৰী কাংশাং',
        'gameplay.aimAndStrikeVoice': 'লক্ষ্য স্থিৰ কৰিবলৈ টানক আৰু মাৰক • মাত: ',
        'gameplay.aimAndStrike': 'ৰাউণ্ড {round} / {total} • লক্ষ্য আৰু আঘাত',
        'gameplay.tapOnTarget': 'লক্ষ্যত টিপক! 🎯',
        'gameplay.tapTargetHint': 'ইঙ্গিত: লক্ষ্য বৃত্তটোত টিপক',
        'gameplay.danceStages': 'নৃত্যৰ স্তৰ (১–৬)',
        'gameplay.doneCount': 'সম্পন্ন: {count}',
        'gameplay.findItem': 'এই বস্তুটো বিচাৰক',
        'gameplay.findItems': 'সকলো {count} টা বস্তু বিচাৰক',
        'gameplay.memorizeItem': 'বস্তুটো মনত ৰাখক',
        'gameplay.imReady': 'মই প্ৰস্তুত!',
        'gameplay.toggleSound': 'শব্দ অন/অফ কৰক',
        'gameplay.pauseResumeGame': 'খেল স্থগিত বা অব্যাহত ৰাখক',
        'gameplay.exitToHome': 'ঘৰলৈ উভতি যাওক',
        'gameplay.closeCall': 'খুবেই ওচৰ! মনোযোগ ৰাখক',
        'gameplay.gentlePush': 'লাহেকৈ ঠেলক! অলপ আগুৱাই দিয়ক',
        'gameplay.goodForce': 'ভাল শক্তি! অলপ কোমল পৰশ চেষ্টা কৰক',
    },
    'bn': {
        'header.todayReminders': 'আজকের অনুস্মারক',
        'games.letPlay': 'চলুন খেলি',
        'gameplay.finalScore': 'চূড়ান্ত স্কোর',
        'gameplay.bestScore': 'সেরা স্কোর',
        'gameplay.home': 'হোম',
        'gameplay.playAgain': 'আবার খেলুন',
        'gameplay.greatJob': 'দারুণ কাজ!',
        'gameplay.activityCompleted': 'কার্যক্রম সমাপ্ত হয়েছে',
        'gameplay.gamePaused': 'খেলা স্থগিত',
        'gameplay.resumeSession': 'খেলা পুনরায় শুরু করুন',
        'gameplay.endSession': 'খেলা শেষ করুন',
        'gameplay.sayVoice': 'বলুন ',
        'gameplay.pauseVoiceHint': '"শুরু করুন" বা "হোম" বলুন',
        'gameplay.accuracy': 'নির্ভুলতা',
        'gameplay.avgSpeed': 'গড় গতি',
        'gameplay.bestStreak': 'টানা সেরা স্কোর',
        'gameplay.level': 'লেভেল {level}',
        'gameplay.round': 'রাউন্ড {round} / {total}',
        'gameplay.trial': 'চেষ্টা {trial} / {total}',
        'gameplay.stage': 'পর্যায় {stage}',
        'gameplay.step': 'ধাপ {step} / {total}',
        'gameplay.getReady': 'প্রস্তুত হন',
        'gameplay.memorizeTiles': '{count}টি টাইল মনে রাখুন',
        'gameplay.rememberAndRecognize': 'মনে রাখুন এবং পরবর্তী স্ক্রিনে শনাক্ত করুন',
        'gameplay.selectDifficulty': 'কঠিনতার স্তর নির্বাচন করুন',
        'gameplay.difficultySettings': 'কঠিনতার সেটিংস',
        'gameplay.chooseStartingChallenge': 'শুরুর চ্যালেঞ্জ বেছে নিন (১ থেকে ১২)',
        'gameplay.difficultyPreset': 'কঠিনতার প্রিসেট (১–১০)',
        'gameplay.traditionalKang': 'ঐতিহ্যবাহী মণিপুরী কাংশাং',
        'gameplay.aimAndStrikeVoice': 'টিপ করতে পিছ টানুন ও আঘাত করুন • কণ্ঠ: ',
        'gameplay.aimAndStrike': 'রাউন্ড {round} / {total} • টিপ ও আঘাত',
        'gameplay.tapOnTarget': 'টার্গেটে ট্যাপ করুন! 🎯',
        'gameplay.tapTargetHint': 'ইঙ্গিত: টার্গেট বৃত্তে ট্যাপ করুন',
        'gameplay.danceStages': 'নাচের পর্যায় (১–৬)',
        'gameplay.doneCount': 'সম্পন্ন: {count}',
        'gameplay.findItem': 'এই আইটেমটি খুঁজুন',
        'gameplay.findItems': 'সবগুলি {count}টি আইটেম খুঁজুন',
        'gameplay.memorizeItem': 'আইটেম মনে রাখুন',
        'gameplay.imReady': 'আমি প্রস্তুত!',
        'gameplay.toggleSound': 'শব্দ চালু/বন্ধ করুন',
        'gameplay.pauseResumeGame': 'খেলা থামান বা চালু করুন',
        'gameplay.exitToHome': 'হোমে ফিরে যান',
        'gameplay.closeCall': 'খুব কাছাকাছি! মনোযোগ বজায় রাখুন',
        'gameplay.gentlePush': 'হালকা ধাক্কা! আরেকটু দূরে এগিয়ে দিন',
        'gameplay.goodForce': 'ভালো শক্তি! আরেকটু নরমভাবে ছুঁয়ে দেখুন',
    },
    'lus': {
        'header.todayReminders': 'Vawiin Hriattirnate',
        'games.letPlay': 'I infiam ang u',
        'gameplay.finalScore': 'POINT HMUH ZAT',
        'gameplay.bestScore': 'POINT THA BER',
        'gameplay.home': 'In',
        'gameplay.playAgain': 'Khel leh rawh',
        'gameplay.greatJob': 'I ti ṭha hle mai!',
        'gameplay.activityCompleted': 'Hna thawh zawh a ni',
        'gameplay.gamePaused': 'Game tihtawp lailawk a ni',
        'gameplay.resumeSession': 'Chhunzawm leh rawh',
        'gameplay.endSession': 'Game titawp rawh',
        'gameplay.sayVoice': 'Sawi rawh ',
        'gameplay.pauseVoiceHint': '"Chhunzawm" emaw "In" sawi rawh',
        'gameplay.accuracy': 'Dikna',
        'gameplay.avgSpeed': 'Chak lam chawhrual',
        'gameplay.bestStreak': 'Tluang ber',
        'gameplay.level': 'Level {level}',
        'gameplay.round': 'Round {round} / {total}',
        'gameplay.trial': 'Trial {trial} / {total}',
        'gameplay.stage': 'Chhawng {stage}',
        'gameplay.step': 'Kalphung {step} / {total}',
        'gameplay.getReady': 'Inring rawh',
        'gameplay.memorizeTiles': 'Tile {count} hi vawng rawh',
        'gameplay.rememberAndRecognize': 'Screen dawtah hian hre rengin thlang chhuak rawh',
        'gameplay.selectDifficulty': 'A harsa zawng thlang rawh',
        'gameplay.difficultySettings': 'Har zâwng innghahna',
        'gameplay.chooseStartingChallenge': 'Inṭan nan a harsa zâwng thlang rawh (1 aṭanga 12)',
        'gameplay.difficultyPreset': 'Har zâwng ruahman sa (1–10)',
        'gameplay.traditionalKang': 'Hnam zia Manipuri Kangshang',
        'gameplay.aimAndStrikeVoice': 'Tin zawn nan hnuk la kap rawh • Aw: ',
        'gameplay.aimAndStrike': 'Round {round} / {total} • Tin la kap rawh',
        'gameplay.tapOnTarget': 'Tin zawn la hmet rawh! 🎯',
        'gameplay.tapTargetHint': 'Hriattirna: A bial lai hi hmet rawh',
        'gameplay.danceStages': 'Lâm Chhawng (1–6)',
        'gameplay.doneCount': 'Zo tawh: {count}',
        'gameplay.findItem': 'He thil hi zawng rawh',
        'gameplay.findItems': 'Thil {count} zawng zawng hi zawng rawh',
        'gameplay.memorizeItem': 'Vawng rawh',
        'gameplay.imReady': 'Ka inpeih e!',
        'gameplay.toggleSound': 'Ri on/off rawh',
        'gameplay.pauseResumeGame': 'Game tihtawp/chhunzawm',
        'gameplay.exitToHome': 'In lamah haw rawh',
        'gameplay.closeCall': 'A ṭhelh ṭhelh! Chithat rawh',
        'gameplay.gentlePush': 'Dim tein nawr rawh! Tlem nawr thui deuh rawh',
        'gameplay.goodForce': 'A tha a chak! Dim deuh hlek rawh',
    },
    'mni': {
        'header.todayReminders': 'ঙসিগী রিমাইন্দারশিং',
        'games.letPlay': 'শান্নসি লাউ',
        'gameplay.finalScore': 'অরোইবা স্কোর',
        'gameplay.bestScore': 'খ্বাইদগী ফবা স্কোর',
        'gameplay.home': 'য়ুম',
        'gameplay.playAgain': 'অমুক্কা শান্নৌ',
        'gameplay.greatJob': 'য়াম্না ফরে!',
        'gameplay.activityCompleted': 'থৌরম লোইশিনখ্রে',
        'gameplay.gamePaused': 'শান্নবা লেপখি',
        'gameplay.resumeSession': 'অমুক্কা চত্থৌ',
        'gameplay.endSession': 'শান্নবা লোইশিল্লু',
        'gameplay.sayVoice': 'হায়বীয়ু ',
        'gameplay.pauseVoiceHint': '"চত্থৌ" নত্রগা "য়ুম" হায়বীয়ু',
        'gameplay.accuracy': 'চুম্বা',
        'gameplay.avgSpeed': 'চাংচত স্পীদ',
        'gameplay.bestStreak': 'খ্বাইদগী ফবা লেপতনবা',
        'gameplay.level': 'থাক {level}',
        'gameplay.round': 'রাউন্দ {round} / {total}',
        'gameplay.trial': 'হোৎনবা {trial} / {total}',
        'gameplay.stage': 'তাঙ্কক {stage}',
        'gameplay.step': 'খোঙথাং {step} / {total}',
        'gameplay.getReady': 'থৌরাং তৌবা',
        'gameplay.memorizeTiles': 'তাইল {count} অসি নীংশিংবীয়ু',
        'gameplay.rememberAndRecognize': 'নীংশিংবীয়ু অমসুং তুংগী স্ক্রিন্দা মশক খঙদোকউ',
        'gameplay.selectDifficulty': 'লুবা থাক খনবীয়ু',
        'gameplay.difficultySettings': 'লুবা থাককী সেটিংস',
        'gameplay.chooseStartingChallenge': 'হৌদোকপগী শিংনবা খনবীয়ু (১ দগী ১২)',
        'gameplay.difficultyPreset': 'লুবা থাককী প্রিসেট (১–১০)',
        'gameplay.traditionalKang': 'হৌনবী মণিপুরী কাংশাং',
        'gameplay.aimAndStrikeVoice': 'পান্দম থম্নবা চীংশিল্লু অমসুং থাদোকউ • খোন্থোক: ',
        'gameplay.aimAndStrike': 'রাউন্দ {round} / {total} • পান্দম অমসুং থাদোকপা',
        'gameplay.tapOnTarget': 'পান্দমদা নাম্মু! 🎯',
        'gameplay.tapTargetHint': 'খঙহঞ্জবা: পান্দম মকোন্দা নাম্মু',
        'gameplay.danceStages': 'জগোই তাঙ্কক (১–৬)',
        'gameplay.doneCount': 'লোইরে: {count}',
        'gameplay.findItem': 'পোৎলম অসি থীবীয়ু',
        'gameplay.findItems': 'পোৎলম {count} মক থীবীয়ু',
        'gameplay.memorizeItem': 'পোৎলম নীংশিংবীয়ু',
        'gameplay.imReady': 'ঐ থৌরাং তৌরে!',
        'gameplay.toggleSound': 'খোন্থোক অন/ওফ তৌবীয়ু',
        'gameplay.pauseResumeGame': 'শান্নবা লেপপা/চত্থবা',
        'gameplay.exitToHome': 'য়ুমদা হনবা',
        'gameplay.closeCall': 'য়াম্না নাকশিনরে! পুকচেল থম্মু',
        'gameplay.gentlePush': 'তপ্না থৌগল্লু! খরসু মাংলোন্দা চীংশিল্লু',
        'gameplay.goodForce': 'ফবা শক্তি! তপ্না থাদোকপা হোৎনৌ',
    }
}

# Now insert inside strings = { ... }
strings_start = code.find("static const Map<String, Map<String, String>> strings = {")
if strings_start == -1:
    print("Could not find strings start")
    exit(1)

strings_part = code[strings_start:]

for lang, kdict in new_keys.items():
    # Find block within strings_part
    # e.g. 'en': {
    m = re.search(rf"('{lang}':\s*\{{)(.*?)(\n    \}},|\n  \}};\n)", strings_part, re.DOTALL)
    if not m:
        print(f"Failed to find lang {lang} in strings")
        continue
    prefix = m.group(1)
    body = m.group(2)
    suffix = m.group(3)

    added = []
    for k, v in kdict.items():
        if f"'{k}':" not in body:
            esc_v = v.replace("'", "\\'")
            added.append(f"      '{k}': '{esc_v}',")
    
    if added:
        new_body = body + "\n      // Gameplay & Game Dialogs\n" + "\n".join(added)
        strings_part = strings_part[:m.start()] + prefix + new_body + suffix + strings_part[m.end():]
        print(f"Added {len(added)} strings to {lang}")

code = code[:strings_start] + strings_part

with open(translations_file, 'w', encoding='utf-8') as f:
    f.write(code)

print("Finished cleanly updating app_translations.dart")
